name: FibraApp
options:
  bundleIdPrefix: com.projeto
targets:
  FibraApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "1.8"
        CFBundleVersion: "8"
        UILaunchStoryboardName: "LaunchScreen"
        UIRequiresFullScreen: true
        NSLocationWhenInUseUsageDescription: "O GPS nativo e necessario para te localizar no mapa."
        NSLocationAlwaysAndWhenInUseUsageDescription: "O GPS nativo e necessario para te localizar no mapa."
    settings:
      MARKETING_VERSION: "1.8"
      CURRENT_PROJECT_VERSION: "8"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_BITCODE: NO
    dependencies:
      - framework: Mobile.xcframework
        embed: true
